# ButtonStatus.srv
# Request
int32 robot_id
int32 button_id
---
# Response
int32 robot_id
int32 button_id
bool success
float32 x
float32 y
float32 size
bool is_pressed
builtin_interfaces/Time timestamp

# x: 0~1
# y: 0~1
# size: 0~1

# button_id values:
# 0: (현재 유일하게 감지되는 버튼)
# 버튼이 2개 이상 감지될 경우 success=false
# 1: 1층
# 2: 2층
# 3: 3층
# 4: 4층
# 5: 5층
# 6: 6층
# 7: 7층
# 8: 8층
# 9: 9층
# 10: 10층
# 11: 11층
# 12: 12층
# 13: B1층
# 14: B2층
# 100: 하행버튼
# 101: 상행버튼
# 102: 열기버튼
# 103: 닫기버튼 